import test from 'node:test';
import assert from 'node:assert/strict';
import { visibleField, validateVerification, copyVerificationFields, safeEvidenceUrl, parseVerificationData } from './verification.ts';
const field = { key:'n', label:'Count',type:'number',min:0, step:1,visibleWhen:{field:'works',values:['Selected']} };
test('worker counts appear only for selected works',()=>{assert.equal(visibleField(field,{works:[]}),false);assert.equal(visibleField(field,{works:['Selected']}),true);});
test('hidden required fields do not block submission',()=>{const schema={sections:[{key:'s',title:'S',fields:[{...field,required:true}]}]};assert.deepEqual(validateVerification(schema,{works:[]}),{});assert.ok(validateVerification(schema,{works:['Selected']}).n);});
test('counts reject negatives and fractions but preserve unknown blanks',()=>{const schema={sections:[{key:'s',title:'S',fields:[field]}]};assert.ok(validateVerification(schema,{works:['Selected'],n:'-1'}).n);assert.ok(validateVerification(schema,{works:['Selected'],n:'2.5'}).n);assert.deepEqual(validateVerification(schema,{works:['Selected'],n:''}),{});});
test('copy contact mappings preserve unrelated answers and permit blanks',()=>{assert.deepEqual(copyVerificationFields({a:'Contact',b:'Old',c:'Other'},{b:'a',d:'missing'}),{a:'Contact',b:'Contact',c:'Other',d:''});});
test('safe evidence links reject active and protocol-relative URLs',()=>{assert.equal(safeEvidenceUrl('javascript:alert(1)'),undefined);assert.equal(safeEvidenceUrl('//evil.com'),undefined);assert.equal(safeEvidenceUrl('/uploads/a.pdf'),'/uploads/a.pdf');assert.equal(safeEvidenceUrl('https://www.tarmeer.com/uploads/a.pdf'),'https://www.tarmeer.com/uploads/a.pdf');});
test('malformed saved data is rejected rather than silently discarded',()=>{assert.throws(()=>parseVerificationData('{bad'));assert.deepEqual(parseVerificationData('{"x":"ok"}'),{x:'ok'});});
test('facility evidence stays hidden for no facilities and reveals actual selected facility',()=>{const f={...field,visibleWhen:{field:'f',excludeValues:['None']}};assert.equal(visibleField(f,{}),false);assert.equal(visibleField(f,{f:['None']}),false);assert.equal(visibleField(f,{f:['Joinery']}),true);});
test('custom work counts follow non-empty trimmed descriptions',()=>{const f={...field,visibleWhen:{field:'custom',notEmpty:true}};assert.equal(visibleField(f,{custom:'  '}),false);assert.equal(visibleField(f,{custom:'Water feature'}),true);});
test('numeric saved answers retain visible values and invalid shapes fail explicitly',()=>{assert.deepEqual(parseVerificationData({n:0,a:[{x:3}]}),{n:'0',a:[{x:'3'}]});assert.throws(()=>parseVerificationData({n:{unexpected:true}}));});

test('confirmed stale draft 404 removes only matching references and resumes new-draft flow once',async()=>{
  const { restoreStoredVerificationDraft }=await import('./verification.ts');
  const entries=new Map([['field_draft_id_ae','41'],['field_draft_id','41'],['field_draft_id_vn','99']]);
  const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};
  const cleared=[];let requests=0;let creates=0;
  const draft=await restoreStoredVerificationDraft(storage,'ae',async id=>{requests++;assert.equal(id,41);throw Object.assign(new Error('Not found'),{status:404});},id=>cleared.push(id));
  if(!draft){creates++;entries.set('field_draft_id_ae','42');}
  assert.equal(requests,1);assert.equal(creates,1);assert.deepEqual(cleared,[41]);assert.equal(entries.get('field_draft_id'),undefined);assert.equal(entries.get('field_draft_id_vn'),'99');assert.equal(entries.get('field_draft_id_ae'),'42');
});
test('403 and network failures preserve stored draft and its credential',async()=>{
  const { restoreStoredVerificationDraft }=await import('./verification.ts');
  for(const error of [Object.assign(new Error('Forbidden'),{status:403}),new Error('Network failure')]){
    const entries=new Map([['field_draft_id_ae','41'],['field_draft_id','41']]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};let cleared=0;
    await assert.rejects(()=>restoreStoredVerificationDraft(storage,'ae',async()=>{throw error;},()=>cleared++),e=>e===error);
    assert.equal(entries.get('field_draft_id_ae'),'41');assert.equal(entries.get('field_draft_id'),'41');assert.equal(cleared,0);
  }
});
test('stale resolution does not erase a newer draft chosen during request',async()=>{
  const { restoreStoredVerificationDraft }=await import('./verification.ts');
  const entries=new Map([['field_draft_id_ae','41'],['field_draft_id','41']]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};
  await restoreStoredVerificationDraft(storage,'ae',async()=>{entries.set('field_draft_id_ae','42');entries.set('field_draft_id','42');throw {status:404};},()=>{});
  assert.equal(entries.get('field_draft_id_ae'),'42');assert.equal(entries.get('field_draft_id'),'42');
});

test('initial 401 clears only selected field token, preserves admin token and draft capability',async()=>{
  const { captureVerificationAuth, recoverVerificationAuthentication }=await import('./verification.ts');
  const entries=new Map([['field_token','expired-field'],['admin_token','admin-session'],['field_draft_id','41'],['field_draft_access_41','capability'],['field_user','country-data']]);
  const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};
  const auth=captureVerificationAuth(storage);assert.deepEqual(auth,{key:'field_token',token:'expired-field'});
  const url=recoverVerificationAuthentication({status:401},storage,auth,null);assert.equal(url,'/field/login?return=%2Ffield%2Fsurvey');
  assert.equal(entries.get('field_token'),undefined);assert.equal(entries.get('admin_token'),'admin-session');assert.equal(entries.get('field_draft_id'),'41');assert.equal(entries.get('field_draft_access_41'),'capability');assert.equal(entries.get('field_user'),'country-data');
});
test('admin-only 401 recovery clears admin token and preserves edit return path',async()=>{
  const { captureVerificationAuth, recoverVerificationAuthentication }=await import('./verification.ts');
  const entries=new Map([['admin_token','expired-admin'],['field_draft_id','41']]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};
  assert.equal(recoverVerificationAuthentication({status:401},storage,captureVerificationAuth(storage),17),'/field/login?return=%2Ffield%2Fsurvey%3Fedit%3D17');assert.equal(entries.get('admin_token'),undefined);assert.equal(entries.get('field_draft_id'),'41');
});
test('403,404 and network errors do not clear authentication or trigger sign-in',async()=>{
  const { captureVerificationAuth, recoverVerificationAuthentication }=await import('./verification.ts');
  for(const error of [{status:403},{status:404},new Error('Network')]){const entries=new Map([['field_token','session']]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};assert.equal(recoverVerificationAuthentication(error,storage,captureVerificationAuth(storage),null),null);assert.equal(entries.get('field_token'),'session');}
});
test('late 401 cannot clear a refreshed authentication token',async()=>{
  const { captureVerificationAuth, recoverVerificationAuthentication }=await import('./verification.ts');
  const entries=new Map([['field_token','expired']]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};const captured=captureVerificationAuth(storage);entries.set('field_token','refreshed');recoverVerificationAuthentication({status:401},storage,captured,null);assert.equal(entries.get('field_token'),'refreshed');
});

test('backend invalid-link resolves exact schema label and correct step',async()=>{
 const {resolveVerificationIssue}=await import('./verification.ts');const schema={sections:[{key:'first',title:'One',fields:[]},{key:'second',title:'Two',fields:[{key:'dynamic_map',label:'Google Maps Link',type:'url'}]}]};assert.deepEqual(resolveVerificationIssue(schema,{dynamic_map:'bad'},Object.assign(new Error('Google Maps Link: invalid link.'),{status:400})),{key:'dynamic_map',label:'Google Maps Link',message:'Google Maps Link: invalid link.',step:1});
});
test('generic network/auth errors do not invent field targets, explicit attachment failure does',async()=>{
 const {resolveVerificationIssue}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'file',label:'Evidence',type:'attachment'}]}]};assert.equal(resolveVerificationIssue(schema,{},new Error('Network failed')),null);assert.equal(resolveVerificationIssue(schema,{},Object.assign(new Error('Evidence: failed'),{status:401}),'file'),null);assert.equal(resolveVerificationIssue(schema,{},Object.assign(new Error('Too large'),{status:413}),'file').key,'file');
});
test('duplicate server labels choose only an unambiguous invalid answer',async()=>{
 const {resolveVerificationIssue}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'a',label:'Count',type:'number',min:0},{key:'b',label:'Count',type:'number',min:0}]}]};const error=Object.assign(new Error('Count: invalid number.'),{status:400});assert.equal(resolveVerificationIssue(schema,{a:'1',b:'-1'},error).key,'b');assert.equal(resolveVerificationIssue(schema,{a:'-1',b:'-1'},error),null);
});
test('DOM navigation focuses control after locating exact field without selector interpolation',async()=>{
 const {focusVerificationField}=await import('./verification.ts');const calls=[];const target={dataset:{fieldKey:'a"[]'},scrollIntoView:()=>calls.push('scroll'),querySelector:()=>({focus:options=>calls.push(options.preventScroll?'focus':'wrong')})};const document={querySelectorAll:()=>[{dataset:{fieldKey:'a'},scrollIntoView:()=>assert.fail('wrong field')},target]};assert.equal(focusVerificationField(document,'a"[]'),true);assert.deepEqual(calls,['scroll','focus']);assert.equal(focusVerificationField(document,'unknown'),false);
});
test('longest label prefix avoids targeting an unrelated shorter label',async()=>{const {resolveVerificationIssue}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'a',label:'Location',type:'text'},{key:'b',label:'Location: Google Maps',type:'url'}]}]};assert.equal(resolveVerificationIssue(schema,{},Object.assign(new Error('Location: Google Maps: invalid link.'),{status:400})).key,'b');});
test('repeat child backend failure targets its owning root field',async()=>{const {resolveVerificationIssue}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'dynamic_rows',label:'Areas',type:'repeat',fields:[{key:'child',label:'District link',type:'url'}]}]}]};const issue=resolveVerificationIssue(schema,{dynamic_rows:[{child:'https://valid.test'},{child:'bad'}]},Object.assign(new Error('District link: invalid link.'),{status:400}));assert.equal(issue.key,'dynamic_rows');assert.equal(issue.label,'Areas / District link');});
test('hidden conditional errors focus a visible controller rather than dead field',async()=>{const {verificationIssueFocusKey}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'enabled',label:'Toggle',type:'checkbox'},{key:'child',label:'Link',type:'url',visibleWhen:{field:'enabled',values:['Yes']}}]}]};assert.equal(verificationIssueFocusKey(schema,{enabled:[]},{key:'child'}),'enabled');assert.equal(verificationIssueFocusKey(schema,{enabled:['Yes']},{key:'child'}),'child');});

test('policy dates reject early years and invalid calendar dates while allowing leap days',async()=>{const {validateVerification}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'dynamic_date',label:'Date',type:'date',datePolicy:{minYear:1900,maxYearsFromToday:0,timeZone:'Asia/Dubai'}}]}]};for(const value of ['0003-08-01','0002-12-01','2025-02-29','2026-04-31'])assert.ok(validateVerification(schema,{dynamic_date:value},new Date('2026-10-07T00:00:00Z')).dynamic_date,value);assert.deepEqual(validateVerification(schema,{dynamic_date:'2024-02-29'},new Date('2026-10-07T00:00:00Z')),{});});
test('Dubai date boundary sets native max from Dubai day rather than browser day',async()=>{const {verificationFieldBounds}=await import('./verification.ts');const field={key:'d',label:'Date',type:'date',datePolicy:{minYear:1900,maxYearsFromToday:0,timeZone:'Asia/Dubai'}};assert.deepEqual(verificationFieldBounds(field,new Date('2026-10-07T21:00:00Z')),{min:'1900-01-01',max:'2026-10-08'});});
test('policy expiry and start permit past dates but enforce future horizons with leap clamp',async()=>{const {verificationFieldBounds,validateVerification}=await import('./verification.ts');const field={key:'d',label:'Date',type:'date',datePolicy:{minYear:1900,maxYearsFromToday:5,timeZone:'Asia/Dubai'}};assert.equal(verificationFieldBounds(field,new Date('2024-02-29T08:00:00Z')).max,'2029-02-28');const schema={sections:[{key:'s',title:'S',fields:[field]}]};assert.deepEqual(validateVerification(schema,{d:'2020-01-01'},new Date('2026-10-07T00:00:00Z')),{});assert.ok(validateVerification(schema,{d:'2031-10-08'},new Date('2026-10-07T00:00:00Z')).d);});
test('established-year policy allows optional blanks and rejects0003/future year without field-key coupling',async()=>{const {validateVerification,verificationFieldBounds}=await import('./verification.ts');const field={key:'any_year',label:'Year',type:'number',step:1,yearPolicy:{min:1900,maxCurrentYear:true,timeZone:'Asia/Dubai'}};const schema={sections:[{key:'s',title:'S',fields:[field]}]};const today=new Date('2026-10-07T00:00:00Z');assert.deepEqual(verificationFieldBounds(field,today),{min:1900,max:2026});for(const value of ['0003','2027'])assert.ok(validateVerification(schema,{any_year:value},today).any_year);assert.deepEqual(validateVerification(schema,{any_year:''},today),{});});
test('structured semantic errors resolve only a known live schema key without questionnaire coupling',async()=>{const {resolveVerificationIssue}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'dynamic_limit',label:'Maximum',type:'number'}]}]};const issue=resolveVerificationIssue(schema,{},Object.assign(new Error('Minimum exceeds maximum.'),{status:400,fieldKey:'dynamic_limit'}));assert.equal(issue.key,'dynamic_limit');assert.equal(resolveVerificationIssue(schema,{},Object.assign(new Error('Minimum exceeds maximum.'),{status:400,fieldKey:'unknown'})),null);});
test('year policy rejects exponent and extra leading-zero representations while generic counts remain numeric',()=>{const field={key:'y',label:'Year',type:'number',step:1,yearPolicy:{min:1900,maxCurrentYear:true,timeZone:'Asia/Dubai'}};const schema={sections:[{key:'s',title:'S',fields:[field]}]};for(const value of ['02026','2e3'])assert.ok(validateVerification(schema,{y:value},new Date('2026-10-07T00:00:00Z')).y,value);assert.deepEqual(validateVerification({sections:[{key:'s',title:'S',fields:[{key:'n',label:'Count',type:'number',min:0}]}]},{n:'2e3'}),{});});

test('UAE phone policy preserves permitted formats but rejects alphabets, invalidprefix and wronglength',()=>{const field={key:'dynamic_phone',label:'Phone',type:'tel',inputPolicy:{kind:'phone',country:'ae',maxLength:40}};const schema={sections:[{key:'s',title:'S',fields:[field]}]};for(const value of ['050 123 4567','+971 50 123 4567','00971-50-123-4567','04 123 4567','+971 4 123 4567'])assert.deepEqual(validateVerification(schema,{dynamic_phone:value}),{},value);for(const value of ['0501234567ABC','0511234567','+97150','05012345678901','+8613812345678'])assert.ok(validateVerification(schema,{dynamic_phone:value}).dynamic_phone,value);});
test('names and addresses require meaningful Unicode letters while identifiers permit numerictext',()=>{const schema={sections:[{key:'s',title:'S',fields:[{key:'n',label:'Name',type:'text',inputPolicy:{kind:'name',minLength:2,maxLength:120,requireLetter:true}},{key:'a',label:'Address',type:'text',inputPolicy:{kind:'address',minLength:5,maxLength:300,requireLetter:true}},{key:'id',label:'License',type:'text',inputPolicy:{kind:'identifier',maxLength:80}}]}]};for(const n of ['3M','محمد','李明'])assert.deepEqual(validateVerification(schema,{n,a:'شارع دبي 123',id:'123456'}),{});assert.ok(validateVerification(schema,{a:'123456'}).a);assert.ok(validateVerification(schema,{n:'123'}).n);});
test('numeric policies distinguish count integers amountprecision and area caps without keycoupling',()=>{const schema={sections:[{key:'s',title:'S',fields:[{key:'c',label:'Count',type:'number',inputPolicy:{kind:'count',min:0,max:100000,integer:true}},{key:'m',label:'Money',type:'number',inputPolicy:{kind:'amount',min:0,max:1e12,precision:2}},{key:'a',label:'Area',type:'number',inputPolicy:{kind:'area',min:0,max:1e9,precision:3}}]}]};assert.deepEqual(validateVerification(schema,{c:'0',m:'12.50',a:'1.125'}),{});for(const [key,value] of [['c','1.5'],['c','100001'],['m','1.001'],['m','2e3'],['a','1000000001']])assert.ok(validateVerification(schema,{[key]:value})[key]);});
test('optional draft blanks remain acceptable while badnonblank receives policyerror',()=>{const schema={sections:[{key:'s',title:'S',fields:[{key:'p',label:'Phone',type:'tel',required:true,inputPolicy:{kind:'phone',country:'ae',maxLength:40}}]}]};assert.deepEqual(validateVerification(schema,{p:''},new Date(),false),{});assert.ok(validateVerification(schema,{p:'abc'},new Date(),false).p);});
test('amount/area policyprecision overrides old numeric step without rejecting validdecimals',()=>{for(const [kind,precision,value] of [['amount',2,'12.34'],['area',3,'12.345']]){const field={key:'n',label:'Numeric',type:'number',step:1,inputPolicy:{kind,precision,min:0,max:1e9}};assert.deepEqual(validateVerification({sections:[{key:'s',title:'S',fields:[field]}]},{n:value}),{});}});
test('phone normalization supports Arabic/Persian digits and rejects allzero subscriber or internationaltrunk',async()=>{const {validVerificationPhone}=await import('./verification.ts');for(const value of ['٠٥٠١٢٣٤٥٦٧','۰۵۰۱۲۳۴۵۶۷'])assert.equal(validVerificationPhone(value,'ae'),true,value);for(const value of ['0500000000','+9710501234567','0501234567\n'])assert.equal(validVerificationPhone(value,'ae'),false,value);});
test('GoogleMaps requires trusted exactalias paths and preventsuserinfo/suffix spoofing',async()=>{const {validVerificationWebLink}=await import('./verification.ts');for(const value of ['https://maps.app.goo.gl/Abc','https://goo.gl/maps/Abc','https://maps.google.com/?q=Dubai','https://www.google.com/maps/place/Dubai'])assert.equal(validVerificationWebLink(value,'map'),true,value);for(const value of ['https://google.com.evil.test/maps','https://evil@google.com/maps','https://google.com/search','https://maps.app.goo.gl/'])assert.equal(validVerificationWebLink(value,'map'),false,value);});
test('numeric payment terms remain valid free text while meaningful addresses cannot be numeric-only',()=>{const schema={sections:[{key:'s',title:'S',fields:[{key:'notes',label:'Payment',type:'textarea',inputPolicy:{kind:'text',maxLength:10000}},{key:'address',label:'Address',type:'text',inputPolicy:{kind:'address',minLength:5,maxLength:300,requireLetter:true}}]}]};assert.deepEqual(validateVerification(schema,{notes:'50% / 30% / 20%',address:'Building 12'}),{});assert.ok(validateVerification(schema,{address:'123456789'}).address);});
test('metadata websitehandle accepts meaningfulsocialhandle only when policy permits',()=>{const field={key:'social',label:'Website',type:'text',inputPolicy:{kind:'website',allowHandle:true,maxLength:2000}};const schema={sections:[{key:'s',title:'S',fields:[field]}]};assert.deepEqual(validateVerification(schema,{social:'@tarmeer_ae'}),{});for(const social of ['@','@bad handle'])assert.ok(validateVerification(schema,{social}).social);});
test('crash recovery merges only changed keys and preserves rawinvalidphone andfreshserveranswers',async()=>{const {verificationPendingKey,restoreVerificationPending}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const pending={identity,changedKeys:['phone'],data:{phone:'bad raw ABC',name:'stale name'},evidenceChanged:false,revision:3,writeId:'write3'};const entries=new Map([[verificationPendingKey(identity),JSON.stringify(pending)]]);const result=restoreVerificationPending({getItem:key=>entries.get(key)??null},identity,{phone:'saved',name:'fresh name'},[]);assert.equal(result.data.phone,'bad raw ABC');assert.equal(result.data.name,'fresh name');assert.equal(result.pending.revision,3);});
test('pendingcache identity country/id/version isolation refusesmalformedcrossrecord data',async()=>{const {verificationPendingKey,restoreVerificationPending}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const entries=new Map([[verificationPendingKey(identity),JSON.stringify({identity:{...identity,country:'vn'},changedKeys:['x'],data:{x:'wrong'},revision:1,writeId:'write',evidenceChanged:false})]]);assert.throws(()=>restoreVerificationPending({getItem:key=>entries.get(key)??null},identity,{},[]));assert.equal(restoreVerificationPending({getItem:key=>entries.get(key)??null},{...identity,id:8},{name:'saved'},[]).pending,null);});
test('save success removes only matchinglatestwrite while newerrevisioncache remainsrecoverable',async()=>{const {verificationPendingKey,clearVerificationPending}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const entries=new Map([[verificationPendingKey(identity),JSON.stringify({identity,revision:4,writeId:'newer'})]]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};assert.equal(clearVerificationPending(storage,identity,'older'),false);assert.ok(entries.has(verificationPendingKey(identity)));assert.equal(clearVerificationPending(storage,identity,'newer'),true);assert.ok(!entries.has(verificationPendingKey(identity)));});
test('storage quota throws explicit error and doesnotclaim localpersistence',async()=>{const {writeVerificationPending}=await import('./verification.ts');assert.throws(()=>writeVerificationPending({setItem:()=>{throw new Error('Quota exceeded');}},{identity:{id:7,country:'ae',version:'v7'},data:{phone:'bad'},changedKeys:['phone'],evidenceChanged:false,revision:1,writeId:'write'}),/Quota/);});
test('immediate blur/operation flush coalesces and duplicate revision queues one request',async()=>{const {createVerificationSaveQueue}=await import('./verification.ts');const queue=createVerificationSaveQueue();let requests=0;let release;const held=new Promise(resolve=>{release=resolve;});const save=()=>{void queue.run(1,async()=>{requests++;await held;});};queue.flush(save);queue.flush(save);await new Promise(resolve=>setImmediate(resolve));assert.equal(requests,1);const first=queue.existing(1);assert.equal(queue.run(1,()=>{assert.fail('duplicate save');}),first);release();await queue.wait();assert.equal(requests,1);});
test('save queue serializes later revisions and recovers after a failed revision',async()=>{const {createVerificationSaveQueue}=await import('./verification.ts');const queue=createVerificationSaveQueue();const events=[];const first=queue.run(1,async()=>{events.push(1);throw Error('fail');});const second=queue.run(2,async()=>events.push(2));await assert.rejects(first);await second;assert.deepEqual(events,[1,2]);});
test('successful server-save after failed journalwrite removes own previousjournal so recoverycannotrollanswersback',async()=>{const {writeVerificationPending,clearVerificationPending,restoreVerificationPending}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const entries=new Map();let quota=false;const storage={getItem:key=>entries.get(key)??null,setItem:(key,value)=>{if(quota)throw Error('Quota');entries.set(key,value);},removeItem:key=>entries.delete(key)};let persistedWriteId;function persist(data,writeId){writeVerificationPending(storage,{identity,data,changedKeys:['phone'],evidenceChanged:false,revision:1,writeId});persistedWriteId=writeId;}persist({phone:'old invalid'},'A');quota=true;assert.throws(()=>persist({phone:'0501234567'},'B'));assert.equal(persistedWriteId,'A');assert.equal(clearVerificationPending(storage,identity,persistedWriteId),true);assert.equal(restoreVerificationPending(storage,identity,{phone:'0501234567'},[]).data.phone,'0501234567');});
test('current schema guards reject unknownpending keys rather than causing permanent save400',async()=>{const {verificationPendingKey,restoreVerificationPending}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const pending={identity,data:{removed:'rawanswer'},changedKeys:['removed'],evidenceChanged:false,revision:1,writeId:'A'};const raw=JSON.stringify(pending);const storage={getItem:()=>raw};assert.throws(()=>restoreVerificationPending(storage,identity,{},[],new Set(['current'])),/no longer match/);assert.equal(storage.getItem(verificationPendingKey(identity)),raw);});
test('pending repeatedrows use current nestedmetadataallowlist withoutrejectingraw invalidknownanswers',async()=>{const {verificationPendingKey,restoreVerificationPending}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const field={key:'rows',label:'Rows',type:'repeat',fields:[{key:'phone',label:'Phone',type:'tel'}]};const allowed=new Map([['rows',field]]);const base={identity,changedKeys:['rows'],evidenceChanged:false,revision:1,writeId:'A'};const bad=JSON.stringify({...base,data:{rows:[{removed:'raw'}]}});assert.throws(()=>restoreVerificationPending({getItem:()=>bad},identity,{},[],allowed),/row fields/);const good=JSON.stringify({...base,data:{rows:[{phone:'raw invalid letters'}]}});assert.equal(restoreVerificationPending({getItem:()=>good},identity,{},[],allowed).data.rows[0].phone,'raw invalid letters');});
test('completedsubmit cleanup preserves newerother-tab journal and differentdraftselection',async()=>{const {verificationPendingKey,finishVerificationDraft}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const entries=new Map([[verificationPendingKey(identity),JSON.stringify({writeId:'tabB'})],['field_draft_id','8'],['field_draft_id_ae','8']]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};finishVerificationDraft(storage,identity,'tabA',true);assert.ok(entries.has(verificationPendingKey(identity)));assert.equal(entries.get('field_draft_id'),'8');assert.equal(entries.get('field_draft_id_ae'),'8');});
test('completedsubmit cleanup removes only own matching journal and draftpointers',async()=>{const {verificationPendingKey,finishVerificationDraft}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const entries=new Map([[verificationPendingKey(identity),JSON.stringify({writeId:'tabA'})],['field_draft_id','7'],['field_draft_id_ae','7']]);const storage={getItem:key=>entries.get(key)??null,removeItem:key=>entries.delete(key)};finishVerificationDraft(storage,identity,'tabA',true);assert.equal(entries.size,0);});
test('genericidentifiers permit numeric/Unicode references and conventional separators but reject nonsense',()=>{const schema={sections:[{key:'s',title:'S',fields:[{key:'id',label:'Identifier',type:'text',inputPolicy:{kind:'identifier',maxLength:80}}]}]};for(const id of ['123456','CN-123/2026','#123','رخصة-١٢٣'])assert.deepEqual(validateVerification(schema,{id}),{},id);for(const id of ['😀','???','---','<script>'])assert.ok(validateVerification(schema,{id}).id,id);});
test('autosave patch sends only owned changedanswers without stalecompanybinding or unrelatedserverfields',async()=>{const {verificationDraftPatch}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'company',label:'Company',type:'text',role:'company_name'},{key:'phone',label:'Phone',type:'tel'}]}]};const patch=verificationDraftPatch(schema,{company:'Old snapshot',phone:'0501234567'},['phone']);assert.deepEqual(patch,{verification_data:{phone:'0501234567'}});const remote={company:'New remote name',phone:'old',other:'remote change'};assert.deepEqual({...remote,...patch.verification_data},{company:'New remote name',phone:'0501234567',other:'remote change'});assert.equal(verificationDraftPatch(schema,{company:'Typed company'},['company']).company_name,'Typed company');});
test('attachment removal merges freshserverfiles and removes only explicitlyselected URLs',async()=>{const {verificationEvidenceRemovalPatch}=await import('./verification.ts');const files=[{url:'/uploads/old',name:'old'},{url:'/uploads/foreign',name:'foreign added later'}];assert.deepEqual(verificationEvidenceRemovalPatch(files,['/uploads/old']),[{url:'/uploads/foreign',name:'foreign added later'}]);assert.deepEqual(verificationEvidenceRemovalPatch(files,[]),files);});
test('crashrecover explicitattachmentremoval preserves concurrentlyuploaded freshserverevidence',async()=>{const {verificationPendingKey,restoreVerificationPending}=await import('./verification.ts');const identity={id:7,country:'ae',version:'v7'};const pending={identity,data:{},changedKeys:[],evidence:[],evidenceChanged:true,removedEvidenceUrls:['/uploads/remove'],revision:1,writeId:'A'};const files=[{url:'/uploads/remove',name:'remove'},{url:'/uploads/foreign',name:'foreign added later'}];const result=restoreVerificationPending({getItem:()=>JSON.stringify(pending)},identity,{},files);assert.deepEqual(result.evidence,[files[1]]);});
test('autosave removal transport sends explicit idempotent URLdelta, never attachmentreplacement',async()=>{const {verificationDraftPatch}=await import('./verification.ts');const schema={sections:[{key:'s',title:'S',fields:[{key:'p',label:'Phone',type:'tel'}]}]};const patch=verificationDraftPatch(schema,{p:'0501234567'},['p'],['/uploads/remove']);assert.deepEqual(patch,{verification_data:{p:'0501234567'},removed_attachment_urls:['/uploads/remove']});assert.ok(!Object.hasOwn(patch,'attachments'));assert.ok(!Object.hasOwn(patch,'company_ref_id'));});
