#!/usr/bin/env python3
"""Regenerate the complete reviewable input-policy inventory from the catalogue."""
import json,sys
from pathlib import Path
root=Path(__file__).resolve().parents[2]
schema=json.loads((root/'server/dist/lib/verificationV7Schema.json').read_text())
rows=[]
examples={'phone':'050 123 4567 / +971 4 234 5678','name':'王 / A / 3M / شركة دبي','address':'中山路 / شارع دبي','identifier':'123456','website':'https://example.com / @company','map':'https://www.google.com/maps?q=Dubai','text':'50% / 30% / 20%','count':'0 / 100000','amount':'0 / 1234.56','area':'0 / 1234.567','email':'contact@example.com','year':'1900 / current Dubai year','date':'1900-01-01 / resolved maximum','attachment':'Previously uploaded JPG, PNG, WebP or PDF','repeat':'[{"emirate":"Dubai","district":"JVC"}]'}
reasons={'phone':'TDRA national mobile/fixed-line prefix and subscriber structure; retain original formatting.','name':'Unicode letters distinguish names from numbers while allowing single-letter and multilingual names.','address':'Unicode letters reject numeric-only addresses without assuming one country language.','identifier':'Licence identifiers allow Unicode letters/digits and spaces . / # _ -; at least one letter/digit is required; numeric-only identifiers are legitimate.','website':'HTTP(S) links or explicit social handles; reject credentials and localhost hosts.','map':'Exact known Google Maps host/path allowlist; reject spoof suffixes and nonstandard ports.','text':'Bounded free text; numeric percentages and dates remain valid unless scope explicitly requires letters.','count':'Finite nonnegative integer bounded against mistakes and abuse.','amount':'Nonnegative AED amount, two decimal places.','area':'Nonnegative area, three decimal places.','email':'Bounded conventional email syntax.','year':'Company establishment cannot predate 1900 or occur after the current Dubai year.','date':'Strict ISO/Gregorian calendar date with business-specific Dubai date horizon.','attachment':'Files use the capability-checked upload endpoint and verified signature, not arbitrary answer URLs.','repeat':'At most 30 service rows, validated child keys and enum values.'}
def esc(value): return str(value).replace('|',r'\|').replace('\n',' ')
def append(section,field,key):
 policy=field['inputPolicy']; kind=policy['kind']; rules=dict(policy)
 for prop in ('datePolicy','yearPolicy'):
  if prop in field: rules[prop]=field[prop]
 if field.get('required'): rules['requiredOnComplete']=True
 if kind in ('choice','choices'): rules['options']=field['options']; rules['noDuplicates']=kind=='choices'
 if field.get('exclusiveValue'): rules['exclusiveValue']=field['exclusiveValue']
 if kind=='attachment': rules.update(maxBytes=field['maxBytes'],accept=field['accept'])
 if kind=='repeat': rules['maxItems']=field['maxItems']
 example=field['options'][0] if kind=='choice' else json.dumps(field['options'][:1],ensure_ascii=False) if kind=='choices' else examples[kind]
 if policy.get('requireLetter') and kind=='text': example='Electrical installation'
 reason=reasons.get(kind,'Only catalogue-defined enum values are accepted; reject tampering.')
 rows.append('| '+' | '.join(esc(v) for v in [section,key,field['label'],json.dumps(rules,ensure_ascii=False,separators=(',',':')),example,reason])+' |')
 for child in field.get('fields',[]): append(section,child,key+'.'+child['key'])
for section in schema['sections']:
 for field in section['fields']: append(section['title'],field,field['key'])
header="""# V7 input-policy inventory

Generated by `python3 scripts/migrations/generate-verification-v7-policy-inventory.py`; canonical definitions are extracted into the server catalogue, stored in `survey_schema`, and rendered dynamically by clients. This inventory contains all 327 top-level fields plus two service-area child fields. Policies apply only to AE V7; legacy answers and schemas remain unchanged.

Optional empty or whitespace-only answers are allowed. Required values are enforced at submission. Numeric values accept plain decimal notation, never exponent notation. String length uses Unicode code points after trimming; validation does not rewrite answers. Dates use Asia/Dubai and strict YYYY-MM-DD calendar checks: completed dates no later than today, availability at most five years ahead, licence expiry at most thirty years ahead; historical availability and expired licences are allowed. All dates start at 1900-01-01. UAE phone prefixes follow [TDRA guidance](https://tdra.gov.ae/en/consumer-tool-hub/topics/porting-numbers); national 0, +971 and 00971 formats, Arabic digits and common visual separators are accepted, but foreign numbers, invalid prefixes, extensions and all-zero subscribers are rejected. Metadata migration enriches old V7 snapshots while preserving labels, options, custom fields, answers and timestamps.

| Section | Field key | Label | Metadata/rules | Valid examples | Reason |
|---|---|---|---|---|---|
"""
target=root/'docs/testing/verification-v7-input-policies.md'
target.write_text(header+'\n'.join(rows)+'\n')
print(f'Generated {len(rows)} policy inventory rows: {target.relative_to(root)}')
