import { useNavigate } from 'react-router-dom';
import { Helmet } from 'react-helmet-async';
import { Building2, Megaphone, MessageCircle, Store, MapPin, ArrowRight } from 'lucide-react';
import PageContainer from '../components/PageContainer';
import { WHATSAPP_LINK, ADDRESS, GOOGLE_MAPS_URL } from '../lib/constants';
import { trackAnalyticsEvent } from '../lib/analytics';

const PRIMARY = '#b8864a';

const PARTNER_BENEFITS = [
  {
    title: 'Social Media Exposure',
    text: 'Promote your brand through Tarmeer’s established content and social channels.',
    icon: Megaphone,
  },
  {
    title: 'Physical Showroom Presence',
    text: 'Showcase products and materials in real spaces where customers explore design solutions.',
    icon: Store,
  },
  {
    title: 'Qualified Daily Inquiries',
    text: 'Benefit from consistent inbound customer interest generated by our online ecosystem.',
    icon: MessageCircle,
  },
];

const APPLICATION_GUIDE = [
  'Company or brand name',
  'Main product category',
  'Target market in the UAE',
  'Preferred collaboration model',
];

export default function ContactPage() {
  const navigate = useNavigate();
  const handleBack = () => {
    if (window.history.length > 1) navigate(-1);
    else navigate('/');
  };

  return (
    <div className="min-h-screen bg-[#faf9f7]">
      <Helmet>
        <title>Contact Us - Tarmeer</title>
        <meta name="description" content="Get in touch with Tarmeer. Partner with us for interior design, renovation, and fit-out services in the UAE." />
        <meta property="og:title" content="Contact Us - Tarmeer" />
        <meta property="og:description" content="Get in touch with Tarmeer for design and renovation partnerships in UAE." />
        <meta property="og:url" content="https://www.tarmeer.com/contact" />
        <meta property="og:type" content="website" />
        <meta property="og:site_name" content="Tarmeer" />
        <meta property="og:image" content="https://www.tarmeer.com/images/tarmeer_logo.svg" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="Contact Us - Tarmeer" />
        <meta name="twitter:description" content="Get in touch with Tarmeer. Partner with us for interior design, renovation, and fit-out services in the UAE." />
        <meta name="twitter:image" content="https://www.tarmeer.com/images/tarmeer_logo.svg" />
        <meta name="keywords" content="contact tarmeer, interior design partnership, UAE showroom, renovation partner" />
        <meta name="robots" content="index, follow" />
        <link rel="canonical" href="https://www.tarmeer.com/contact" />
        <script type="application/ld+json">{JSON.stringify({
          '@context': 'https://schema.org',
          '@type': 'ContactPage',
          name: 'Contact Tarmeer',
          url: 'https://www.tarmeer.com/contact',
          mainEntity: {
            '@type': 'Organization',
            name: 'Tarmeer',
            url: 'https://www.tarmeer.com',
            telephone: '+971-58-838-8922',
            address: {
              '@type': 'PostalAddress',
              streetAddress: 'Industrial Area 2',
              addressLocality: 'Sharjah',
              addressCountry: 'AE',
            },
            contactPoint: {
              '@type': 'ContactPoint',
              telephone: '+971-58-838-8922',
              contactType: 'customer service',
              availableLanguage: ['English', 'Arabic'],
            },
          },
        })}</script>
      </Helmet>
      <PageContainer className="py-12 sm:py-16">
        <button onClick={handleBack} className="mb-8 inline-block text-sm text-[#c6a065] hover:underline">
          ← Back
        </button>

        <section className="rounded-[22px] border border-stone-200 bg-white p-6 shadow-[0_14px_40px_rgba(28,18,8,0.05)] sm:p-8 lg:p-10">
          <p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-stone-500">
            Partnership Opportunity
          </p>
          <h1 className="font-serif text-3xl font-bold leading-tight text-[#2c2c2c] sm:text-4xl">
            Join Our Showroom Alliance
          </h1>
          <p className="mt-4 max-w-[72ch] text-[15px] leading-7 text-stone-600">
            Expand your brand through Tarmeer’s showroom network, social media ecosystem, and daily customer inquiries. We help partners increase visibility and business opportunities across the UAE.
          </p>

          <div className="mt-7 grid grid-cols-1 gap-3.5 md:grid-cols-3">
            {PARTNER_BENEFITS.map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.title} className="rounded-xl border border-stone-100 bg-stone-50/70 p-4">
                  <div
                    className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg"
                    style={{ backgroundColor: `${PRIMARY}18` }}
                  >
                    <Icon className="h-4.5 w-4.5" style={{ color: PRIMARY }} />
                  </div>
                  <h2 className="text-sm font-semibold text-[#2c2c2c]">{item.title}</h2>
                  <p className="mt-1.5 text-sm leading-6 text-stone-600">{item.text}</p>
                </div>
              );
            })}
          </div>

          <div className="mt-7 grid grid-cols-1 gap-6 lg:grid-cols-[1.15fr_0.85fr]">
            <div className="rounded-xl border border-stone-200 bg-white p-5">
              <h2 className="text-base font-semibold text-[#2c2c2c]">What to include in your inquiry</h2>
              <ul className="mt-3 space-y-2">
                {APPLICATION_GUIDE.map((item) => (
                  <li key={item} className="flex items-start gap-2.5 text-sm text-stone-600">
                    <span className="mt-2 h-1.5 w-1.5 rounded-full" style={{ backgroundColor: PRIMARY }} />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-4 text-xs text-stone-500">
                Ideal for brands, suppliers, and showroom partners looking to scale in the UAE.
              </p>
            </div>

            <div className="rounded-xl border border-stone-200 bg-white p-5">
              <h2 className="text-base font-semibold text-[#2c2c2c]">Contact our partnership team</h2>
              <p className="mt-2 text-sm leading-6 text-stone-600">
                Share your brand profile and collaboration goals. We will review and get back with next steps.
              </p>
              <div className="mt-4 space-y-3">
                <a
                  href={WHATSAPP_LINK}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={() => trackAnalyticsEvent('click_whatsapp', { source: 'contact_partnership' })}
                  className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl text-sm font-bold text-white transition-transform hover:-translate-y-0.5"
                  style={{ backgroundColor: PRIMARY }}
                >
                  Start on WhatsApp
                  <ArrowRight className="h-4 w-4" />
                </a>
                <a
                  href="mailto:partnership@tarmeer.com?subject=Showroom%20Alliance%20Partnership%20Inquiry"
                  onClick={() => trackAnalyticsEvent('submit_contact_form', { source: 'contact_email_link' })}
                  className="inline-flex h-11 w-full items-center justify-center rounded-xl border border-stone-200 bg-stone-50 text-sm font-semibold text-[#2c2c2c] hover:bg-stone-100"
                >
                  Email Partnership Team
                </a>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8 rounded-[20px] border border-stone-200 bg-white p-6 sm:p-8">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-start gap-3 text-stone-600">
              <MapPin className="mt-0.5 h-5 w-5 shrink-0" style={{ color: PRIMARY }} />
              <div>
                <h2 className="text-sm font-semibold text-[#2c2c2c]">Showroom Address</h2>
                <p className="mt-1 text-sm">{ADDRESS}</p>
              </div>
            </div>
            <a
              href={GOOGLE_MAPS_URL}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-stone-200 px-4 text-sm font-semibold text-[#2c2c2c] hover:bg-stone-50"
            >
              <Building2 className="h-4 w-4" />
              View on Map
            </a>
          </div>
        </section>
      </PageContainer>
    </div>
  );
}
