USE tarmeer;

CREATE TABLE IF NOT EXISTS visitor_ip_geo_cache (
  ip VARCHAR(64) PRIMARY KEY,
  location_label VARCHAR(255) DEFAULT NULL,
  country_code VARCHAR(8) DEFAULT NULL,
  country_name VARCHAR(128) DEFAULT NULL,
  region_name VARCHAR(128) DEFAULT NULL,
  city_name VARCHAR(128) DEFAULT NULL,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
