'use client';

import { useRouter } from 'next/navigation';
import { Building2, Megaphone, MessageCircle, Store, MapPin, ArrowRight } from 'lucide-react';
import { ADDRESS, GOOGLE_MAPS_URL, VN_ADDRESS, VN_GOOGLE_MAPS_URL } from '@/lib/constants';
import { trackAnalyticsEvent } from '@/lib/analytics';
import { useSiteLocale } from '@/contexts/SiteLocaleContext';
import { countryFromLang } from '@/lib/country';

const PRIMARY = '#b8864a';

const PARTNER_BENEFITS = [
  {
    title: 'Social Media Exposure',
    text: 'Promote your brand through Tarmeer\'s established content and social channels.',
    icon: Megaphone,
  },
  {
    title: 'Physical Showroom Presence',
    text: 'Showcase products and materials in real spaces where customers explore design solutions.',
    icon: Store,
  },
  {
    title: 'Qualified Daily Inquiries',
    text: 'Benefit from consistent inbound customer interest generated by our online ecosystem.',
    icon: MessageCircle,
  },
];

export default function ContactClient() {
  const router = useRouter();
  const { lang } = useSiteLocale();
  const c = countryFromLang(lang);
  const address = c.code === 'vn' ? VN_ADDRESS : ADDRESS;
  const mapsUrl = c.code === 'vn' ? VN_GOOGLE_MAPS_URL : GOOGLE_MAPS_URL;

  const APPLICATION_GUIDE = [
    'Company or brand name',
    'Main product category',
    `Target market in ${c.name}`,
    'Preferred collaboration model',
  ];

  const contactJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'ContactPage',
    name: 'Contact Tarmeer',
    url: `${c.baseUrl}/contact`,
    mainEntity: {
      '@type': 'Organization',
      name: 'Tarmeer',
      url: c.baseUrl,
      telephone: c.telephone,
      address: {
        '@type': 'PostalAddress',
        addressLocality: c.addressLocality,
        addressCountry: c.isoCode,
      },
      contactPoint: {
        '@type': 'ContactPoint',
        telephone: c.telephone,
        contactType: 'customer service',
      },
    },
  };

  const handleBack = () => {
    if (window.history.length > 1) router.back();
    else router.push('/');
  };

  return (
    <div className="min-h-screen bg-[#faf9f7]">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(contactJsonLd) }}
      />
      <div className="max-w-5xl mx-auto px-4 sm:px-6 py-12 sm:py-16">
        <button onClick={handleBack} className="mb-8 inline-block text-sm text-[#c6a065] hover:underline">
          ← Back
        </button>

        <section className="rounded-[22px] border border-stone-200 bg-white p-6 shadow-[0_14px_40px_rgba(28,18,8,0.05)] sm:p-8 lg:p-10">
          <p className="mb-3 text-[11px] font-semibold uppercase tracking-[0.16em] text-stone-500">
            Partnership Opportunity
          </p>
          <h1 className="font-serif text-3xl font-bold leading-tight text-[#2c2c2c] sm:text-4xl">
            Join Our Showroom Alliance
          </h1>
          <p className="mt-4 max-w-[72ch] text-[15px] leading-7 text-stone-600">
            Expand your brand through Tarmeer&apos;s showroom network, social media ecosystem, and daily customer inquiries. We help partners increase visibility and business opportunities across {c.name}.
          </p>

          <div className="mt-7 grid grid-cols-1 gap-3.5 md:grid-cols-3">
            {PARTNER_BENEFITS.map((item) => {
              const Icon = item.icon;
              return (
                <div key={item.title} className="rounded-xl border border-stone-100 bg-stone-50/70 p-4">
                  <div
                    className="mb-3 flex h-9 w-9 items-center justify-center rounded-lg"
                    style={{ backgroundColor: `${PRIMARY}18` }}
                  >
                    <Icon className="h-4 w-4" style={{ color: PRIMARY }} />
                  </div>
                  <h2 className="text-sm font-semibold text-[#2c2c2c]">{item.title}</h2>
                  <p className="mt-1.5 text-sm leading-6 text-stone-600">{item.text}</p>
                </div>
              );
            })}
          </div>

          <div className="mt-7 grid grid-cols-1 gap-6 lg:grid-cols-[1.15fr_0.85fr]">
            <div className="rounded-xl border border-stone-200 bg-white p-5">
              <h2 className="text-base font-semibold text-[#2c2c2c]">What to include in your inquiry</h2>
              <ul className="mt-3 space-y-2">
                {APPLICATION_GUIDE.map((item) => (
                  <li key={item} className="flex items-start gap-2.5 text-sm text-stone-600">
                    <span className="mt-2 h-1.5 w-1.5 rounded-full" style={{ backgroundColor: PRIMARY }} />
                    <span>{item}</span>
                  </li>
                ))}
              </ul>
              <p className="mt-4 text-xs text-stone-500">
                Ideal for brands, suppliers, and showroom partners looking to scale in {c.name}.
              </p>
            </div>

            <div className="rounded-xl border border-stone-200 bg-white p-5">
              <h2 className="text-base font-semibold text-[#2c2c2c]">Contact our partnership team</h2>
              <p className="mt-2 text-sm leading-6 text-stone-600">
                Share your brand profile and collaboration goals. We will review and get back with next steps.
              </p>
              <div className="mt-4 space-y-3">
                <a
                  href={c.whatsappLink}
                  target="_blank"
                  rel="noopener noreferrer"
                  onClick={() => trackAnalyticsEvent('click_whatsapp', { source: 'contact_partnership' })}
                  className="inline-flex h-11 w-full items-center justify-center gap-2 rounded-xl text-sm font-bold text-white transition-transform hover:-translate-y-0.5"
                  style={{ backgroundColor: PRIMARY }}
                >
                  Start on WhatsApp
                  <ArrowRight className="h-4 w-4" />
                </a>
                <a
                  href="mailto:partnership@tarmeer.com?subject=Showroom%20Alliance%20Partnership%20Inquiry"
                  onClick={() => trackAnalyticsEvent('submit_contact_form', { source: 'contact_email_link' })}
                  className="inline-flex h-11 w-full items-center justify-center rounded-xl border border-stone-200 bg-stone-50 text-sm font-semibold text-[#2c2c2c] hover:bg-stone-100"
                >
                  Email Partnership Team
                </a>
              </div>
            </div>
          </div>
        </section>

        <section className="mt-8 rounded-[20px] border border-stone-200 bg-white p-6 sm:p-8">
          <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
            <div className="flex items-start gap-3 text-stone-600">
              <MapPin className="mt-0.5 h-5 w-5 shrink-0" style={{ color: PRIMARY }} />
              <div>
                <h2 className="text-sm font-semibold text-[#2c2c2c]">Showroom Address</h2>
                <p className="mt-1 text-sm">{address}</p>
              </div>
            </div>
            <a
              href={mapsUrl}
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex h-10 items-center justify-center gap-2 rounded-lg border border-stone-200 px-4 text-sm font-semibold text-[#2c2c2c] hover:bg-stone-50"
            >
              <Building2 className="h-4 w-4" />
              View on Map
            </a>
          </div>
        </section>
      </div>
    </div>
  );
}
